-- Pattern alerts: stores detected market patterns and AI-generated narratives
CREATE TABLE pattern_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_id VARCHAR(100) NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
    title VARCHAR(255) NOT NULL,
    narrative TEXT,
    metric_data TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP
);

CREATE INDEX idx_alerts_coin ON pattern_alerts(coin_id);
CREATE INDEX idx_alerts_created ON pattern_alerts(created_at);
CREATE INDEX idx_alerts_type ON pattern_alerts(pattern_type);

-- User alert read tracking: surrogate PK with unique constraint
CREATE TABLE user_alert_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    alert_id BIGINT NOT NULL,
    read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (alert_id) REFERENCES pattern_alerts(id),
    UNIQUE (user_id, alert_id)
);

CREATE INDEX idx_alert_reads_user ON user_alert_reads(user_id);

-- AI usage tracking: per-user daily budget enforcement
CREATE TABLE ai_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    usage_date DATE NOT NULL,
    tokens_used INT NOT NULL DEFAULT 0,
    request_count INT NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE (user_id, usage_date)
);

CREATE INDEX idx_ai_usage_user_date ON ai_usage(user_id, usage_date);

-- AI request log: per-call diagnostics (append-only, no FK constraints)
CREATE TABLE ai_request_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    endpoint VARCHAR(100) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    tokens_used INT NOT NULL DEFAULT 0,
    duration_ms INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_log_user_date ON ai_request_log(user_id, created_at);

-- Market snapshots: persists pattern detection history across redeploys
CREATE TABLE market_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_data TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
